### ISSUE TITLE
set from unixtimestamp

### ISSUE THREAD

**Issue by axwell** [MarkusLange/Arduino-Due-RTC-Library#1]
Hello Markus,
is there a way to set the time from a unix timestamp ?
This can be useful when requesting time from NTP server.

Thanks !

**Comment by MarkusLange** [comment]
Not atm. I will implement it the next days, but I have no DUE to hand this week so it would be nice if you can give me feedback how it and if it works.

**Comment by axwell** [comment]
Of course!

**Comment by MarkusLange** [comment]
So I have my first shot ready, you find my eMail inside the library mail me and I send you an early version
