### ISSUE TITLE
RTC with leap year

### ISSUE THREAD

**Issue by kapyaar** [MarkusLange/Arduino-Due-RTC-Library#7]
Markus,

Can you please test this library on a Due now? I am finding some issues when setting date, and I think it is probably because of leapyear?

**Comment by MarkusLange** [comment]
Atm i'm rewriting some parts of the library.

Can you describe more details of the issues may with some code

**Comment by kapyaar** [comment]
I am using the example code itself. "Due_RTC_Simple_Unixtime_Compilertime".  Can you check one thing? Is the rtc_clock.unittime() working correctly? I doubt it is not. See below. Time and Date are correct, but UT is not.

Unixtime: 1459012298
And in plain for everyone
Time: 12:11:38
Date: Sat 20.02.2016

**Comment by MarkusLange** [comment]
Uh yes I know this issues since a few days it's inside the unixtime I correct it inside te Due_rtc for now the new lib follows the next days
